/*===========================================================*/
/*====中断处理模块=====================*/
/*===========================================================*/
#include "derivative.h"
//#include "status_st.h" //2014-1-17 peter, modified

/*
typedef union {
  word Word;
   
  struct {
    
    union {
      byte Byte;
    } v_prd_cashSTR;
    #define v_prd_cash                _v_prd_cas.Overlap_STR.v_prd_cashSTR.Byte
    
    union {
      byte Byte;
    } v_prd_caslSTR;
    #define v_prd_casl                _v_prd_cas.Overlap_STR.v_prd_caslSTR.Byte
    
  } Overlap_STR;

} v_prd_casSTR;

#define v_prd_cas                     _v_prd_cas.Word

typedef union {
  word Word;
   
  struct {
    
    union {
      byte Byte;
    } v_t_cas0hSTR;
    #define v_t_cas0h                 _v_t_cas0.Overlap_STR.v_t_cas0hSTR.Byte
    
    union {
      byte Byte;
    } v_t_cas0lSTR;
    #define v_t_cas0l                 _v_t_cas0.Overlap_STR.v_t_cas0lSTR.Byte
    
  } Overlap_STR;

} v_t_cas0STR;
*/
//extern volatile v_prd_casSTR _v_prd_cas @ADD_RAM_v_prd_cas;    
//extern volatile v_t_cas0STR _v_t_cas0 @ADD_RAM_v_t_cas0;




